# Generated by Django 5.1.1 on 2024-10-13 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
