# Generated by Django 5.1.1 on 2024-10-13 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_assignment_assignment_type"),
        ("dashboard", "0002_course_alter_assignment_assignment_type_schedule"),
    ]

    operations = []
