# Generated by Django 5.1.1 on 2024-10-15 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_merge_20241013_2232"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="course_name",
        ),
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.course",
            ),
        ),
    ]
