# Generated by Django 5.1.1 on 2024-10-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_remove_assignment_course_code_alter_assignment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
