# Generated by Django 5.1.1 on 2024-10-15 23:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_alter_assignment_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="course",
            new_name="course_name",
        ),
    ]
