# Generated by Django 5.1.1 on 2024-10-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_rename_course_assignment_course_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateField(null=True),
        ),
    ]
