# Generated by Django 5.1.1 on 2024-10-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_course_course_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("txt", "Text File"), ("pdf", "PDF File")],
                        max_length=3,
                    ),
                ),
                ("file", models.FileField(upload_to="course-files/")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="dashboard.course",
                    ),
                ),
            ],
        ),
    ]
