# Generated by Django 5.1.1 on 2024-10-19 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_coursefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.course'),
        ),
    ]
