# Generated by Django 5.1.1 on 2024-10-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_assignment_user_userassignmentd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAssignmentd',
        ),
    ]
