# Generated by Django 5.1.1 on 2024-10-20 22:21


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0014_userschedule_delete_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
