# Generated by Django 5.1.1 on 2024-10-30 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0015_alter_assignment_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefile",
            name="file_size",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="coursefile",
            name="original_filename",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coursefile",
            name="upload_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="coursefile",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="coursefile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("txt", "Text File"),
                    ("pdf", "PDF File"),
                    ("jpg", "JPG File"),
                ],
                max_length=3,
            ),
        ),
    ]
