# Generated by Django 5.1.1 on 2024-10-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0016_coursefile_file_size_coursefile_original_filename_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefile",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("OTH", "Other"),
                    ("SYL", "Syllabus"),
                    ("SLD", "Slides"),
                    ("PAP", "Past Paper"),
                    ("SOL", "Exam Solution"),
                    ("HWK", "Homework"),
                ],
                default="OTH",
                max_length=3,
            ),
        ),
    ]
