# Generated by Django 5.1.1 on 2024-10-27 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_assignment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('txt', 'Text File'), ('pdf', 'PDF File')], max_length=3)),
                ('file_category', models.CharField(choices=[('TEMP', 'Template'), ('INSTR', 'Instructions'), ('GUIDE', 'Study Guide'), ('READ', 'Reading')], max_length=5)),
                ('file', models.FileField(upload_to='assignment-files/')),
                ('upload_time', models.DateTimeField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.assignment')),
            ],
        ),
    ]
