# Generated by Django 5.1.1 on 2024-10-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0017_coursefile_content_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursefile",
            old_name="original_filename",
            new_name="filename",
        ),
        migrations.AddField(
            model_name="coursefile",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
