# Generated by Django 5.1.1 on 2024-10-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0018_rename_original_filename_coursefile_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefile",
            name="keywords",
            field=models.CharField(
                help_text="Enter keywords separated by commas.",
                max_length=255,
                null=True,
            ),
        ),
    ]
