# Generated by Django 5.1.1 on 2024-10-31 01:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0019_coursefile_keywords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursefile",
            name="file_size",
        ),
    ]
