# Generated by Django 5.1.1 on 2024-10-31 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_assignment_file_alter_assignmentfile_file'),
        ('dashboard', '0020_remove_coursefile_file_size'),
    ]

    operations = [
    ]
