# Generated by Django 5.1.1 on 2024-11-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_merge_20241031_1904'),
        ('dashboard', '0021_merge_20241101_1824'),
    ]

    operations = [
    ]
