# Generated by Django 5.1.1 on 2024-11-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_merge_20241102_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentfile',
            name='file_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
