# Generated by Django 5.1.1 on 2024-11-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0023_assignmentfile_file_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursefile",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("ALL", "All"),
                    ("OTH", "Other"),
                    ("SYL", "Syllabus"),
                    ("SLD", "Slides"),
                    ("PAP", "Past Paper"),
                    ("SOL", "Exam Solution"),
                    ("HWK", "Homework"),
                ],
                default="OTH",
                max_length=3,
            ),
        ),
    ]
