# Generated by Django 5.1.1 on 2024-11-03 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0026_alter_coursefile_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="date_submitted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="assignment",
            name="keywords",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
