# Generated by Django 5.1.1 on 2024-11-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_userschedule_completed_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_submitted',
            field=models.DateTimeField(default=None),
        ),
    ]
