# Generated by Django 5.1.1 on 2024-11-17 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0031_alter_assignment_date_submitted"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AssignmentFile",
        ),
    ]
