# Generated by Django 5.1.1 on 2024-11-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="approved",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ude", "Under Examination"),
                    ("rjt", "Rejected"),
                    ("apv", "Approved"),
                ],
                default="ude",
                max_length=3,
            ),
        ),
    ]
